[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Forzar HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Redirección de www a dominio principal
[[redirects]]
  from = "https://www.olawave.ai/*"
  to = "https://olawave.ai/:splat"
  status = 301
  force = true

# Redirección para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
